version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "00:15"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /cli/
    schedule:
      interval: daily
      time: "00:45"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    groups:
      npm[cli]:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /minifiers
    schedule:
      interval: daily
      time: "01:15"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    groups:
      npm[minifiers]:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /minifiers
    schedule:
      interval: daily
      time: "01:45"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    groups:
      pip[minifiers]:
        patterns:
          - "*"
