version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "00:15"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
        - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "00:45"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: /minifiers
    schedule:
      interval: daily
      time: "01:15"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
