version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"

  # Docker
  - package-ecosystem: docker
    directories:
      - /
    schedule:
      interval: daily
      time: "02:15"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    groups:
      docker:
        patterns:
          - "*"

  # NPM
  - package-ecosystem: npm
    directories:
      - /cli
      - /minifiers
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "02:30"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    groups:
      npm:
        patterns:
          - "*"

  # Pip
  - package-ecosystem: pip
    directories:
      - /minifiers
    schedule:
      interval: daily
      time: "02:45"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    groups:
      pip:
        patterns:
          - "*"
