version: 2.1

workflows:
  version: 2
  circleci:
    jobs:
      - azlint:
          filters:
            branches:
              ignore:
                - main
      - native-build:
          filters:
            branches:
              ignore:
                - main
      - docker-build:
          filters:
            branches:
              ignore:
                - main

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint:0.6.13
    steps:
      - checkout
      - run: azlint

  native-build:
    docker:
      - image: debian:12.11
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apt-get update -qq
            DEBIAN_FRONTEND=noninteractive DEBCONF_TERSE=yes DEBCONF_NOWARNINGS=yes \
              apt-get install -q --yes --no-install-recommends \
              bash bundler git make moreutils nodejs npm patch python3 python3-pip python3-venv \
              autoconf bison build-essential ca-certificates curl moreutils \
              libffi-dev libgdbm-dev libncurses5-dev libreadline-dev libreadline-dev libssl-dev libyaml-dev zlib1g-dev
      - run:
          name: Install gitman
          command: |
            python3 -m pip install --requirement ./docker-utils/dependencies/gitman/requirements.txt --target python-vendor --quiet
      - run:
          name: Install rbenv
          command: |
            export PATH="$PWD/python-vendor/bin:$PATH"
            export PYTHONPATH="$PWD/python-vendor"
            cd ./docker-utils/dependencies/gitman/rbenv-installer
            gitman install --quiet
            cd -
            export RBENV_ROOT="$PWD/.rbenv"
            bash ./docker-utils/dependencies/gitman/rbenv-installer/gitman-repositories/rbenv-installer/bin/rbenv-installer
      - run:
          name: Install ruby
          command: |
            export RBENV_ROOT="$PWD/.rbenv"
            export PATH="/root/.rbenv/bin:$PWD/.rbenv/bin:$PWD/.rbenv/shims:$PATH"
            ruby_version="$(cat .ruby-version)"
            chronic rbenv install "$ruby_version"
            ln -s "$PWD/.rbenv/versions/$ruby_version" "$PWD/.rbenv/versions/current"
      - run:
          name: Install project dependencies
          command: |
            export PATH="$PWD/.rbenv/versions/current/bin:$PATH"
            make bootstrap
      - run:
          name: Build
          command: |
            export PATH="$PWD/.rbenv/versions/current/bin:$PATH"
            make build
      - run:
          name: Test
          command: |
            export PATH="$PWD/.rbenv/versions/current/bin:$PATH"
            make test

  docker-build:
    docker:
      - image: docker:28.3.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker build
          command: docker build . --tag matejkosiarcik/azminifier:dev --progress plain
