version: 2.1

workflows:
  version: 2
  circleci:
    jobs:
      - azlint:
          filters:
            branches:
              ignore:
                - main
      - native-build:
          filters:
            branches:
              ignore:
                - main
      - docker-build:
          filters:
            branches:
              ignore:
                - main

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint:0.6.11
    steps:
      - checkout
      - run: azlint

  native-build:
    docker:
      - image: debian:12.5
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apt-get update -qq
            DEBIAN_FRONTEND=noninteractive DEBCONF_TERSE=yes DEBCONF_NOWARNINGS=yes \
              apt-get install -q --yes --no-install-recommends \
              git make nodejs npm python3 python3-pip python3-venv
      - run:
          name: Install project dependencies
          command: make bootstrap
      - run:
          name: Build
          command: make build
      - run:
          name: Test
          command: make test

  docker-build:
    docker:
      - image: docker:26.1.4
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker build
          command: docker build . --tag matejkosiarcik/unnecessary-minifier:dev --progress plain
