name: Build (docker)

permissions: read-all

on:
  pull_request:

env:
  DOCKER_IMAGE: matejkosiarcik/universal-minifier

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          # x86
          - linux/386
          - linux/amd64
          # ARM
          - linux/arm/v5
          - linux/arm/v7
          - linux/arm64/v8
          # Other
          - linux/ppc64le
          - linux/mips64le
          - linux/s390x

    name: Build ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build
        uses: docker/build-push-action@v6.0.1
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          platforms: ${{ matrix.platform }}
          push: false
          tags: ${{ env.DOCKER_IMAGE }}:dev
