name: Build (native)

permissions: read-all

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.0
        with:
          node-version: latest

      - name: Setup Python
        uses: actions/setup-python@v4.8.0
        with:
          python-version: 3.x

      - name: Bootstrap
        run: make bootstrap
        shell: bash

      - name: Build
        run: make build
        shell: bash

      - name: Test
        run: make test
        shell: bash
