name: Build (native)

permissions: read-all

on:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup NodeJS
        uses: actions/setup-node@v5.0.0
        with:
          node-version: latest

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.x

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.257.0
        with:
          ruby-version: ruby # latest

      - name: Install HomeBrew dependencies
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install bash

      - name: Bootstrap
        shell: bash
        run: make bootstrap

      - name: Test
        shell: bash
        run: make test

      - name: Build
        shell: bash
        run: make build

      - name: Dry Run
        shell: bash
        working-directory: cli
        run: |
          tmpdir="$(mktemp -d)"
          touch "$tmpdir/file.txt"
          npm run run -- "$tmpdir"
          rm -rf "$tmpdir"
