name: Build (native)

permissions: read-all

on:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: latest

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.x

      - name: Bootstrap
        shell: bash
        run: make bootstrap

      - name: Build
        shell: bash
        run: make build

      - name: Dry Run
        shell: bash
        run: |
          cd cli
          tmpdir="$(mktemp -d)"
          npm run run -- "$tmpdir"
          rm -rf "$tmpdir"

      - name: Test
        shell: bash
        run: make test
